/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HoldingRouteImport } from './routes/holding'
import { Route as AberturadeempresaRouteImport } from './routes/aberturadeempresa'
import { Route as IndexRouteImport } from './routes/index'

const HoldingRoute = HoldingRouteImport.update({
  id: '/holding',
  path: '/holding',
  getParentRoute: () => rootRouteImport,
} as any)
const AberturadeempresaRoute = AberturadeempresaRouteImport.update({
  id: '/aberturadeempresa',
  path: '/aberturadeempresa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aberturadeempresa': typeof AberturadeempresaRoute
  '/holding': typeof HoldingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aberturadeempresa': typeof AberturadeempresaRoute
  '/holding': typeof HoldingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aberturadeempresa': typeof AberturadeempresaRoute
  '/holding': typeof HoldingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aberturadeempresa' | '/holding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aberturadeempresa' | '/holding'
  id: '__root__' | '/' | '/aberturadeempresa' | '/holding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AberturadeempresaRoute: typeof AberturadeempresaRoute
  HoldingRoute: typeof HoldingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/holding': {
      id: '/holding'
      path: '/holding'
      fullPath: '/holding'
      preLoaderRoute: typeof HoldingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aberturadeempresa': {
      id: '/aberturadeempresa'
      path: '/aberturadeempresa'
      fullPath: '/aberturadeempresa'
      preLoaderRoute: typeof AberturadeempresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AberturadeempresaRoute: AberturadeempresaRoute,
  HoldingRoute: HoldingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
